[2024-11-20T10:41:08.635+0700] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-11-20T10:41:08.696+0700] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: scrape_twitter.scrape_twitter_task manual__2024-11-20T03:40:58.859380+00:00 [queued]>
[2024-11-20T10:41:08.714+0700] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: scrape_twitter.scrape_twitter_task manual__2024-11-20T03:40:58.859380+00:00 [queued]>
[2024-11-20T10:41:08.715+0700] {taskinstance.py:2866} INFO - Starting attempt 1 of 2
[2024-11-20T10:41:08.744+0700] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): scrape_twitter_task> on 2024-11-20 03:40:58.859380+00:00
[2024-11-20T10:41:08.769+0700] {logging_mixin.py:190} WARNING - /home/fabian4819/REKAYASA DATA/final-exam-etl-pipeline-project/airflow-env/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=126755) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-11-20T10:41:08.772+0700] {standard_task_runner.py:72} INFO - Started process 126999 to run task
[2024-11-20T10:41:08.780+0700] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'scrape_twitter', 'scrape_twitter_task', 'manual__2024-11-20T03:40:58.859380+00:00', '--job-id', '28', '--raw', '--subdir', 'DAGS_FOLDER/scrape_twitter_dag.py', '--cfg-path', '/tmp/tmptnyc96ll']
[2024-11-20T10:41:08.782+0700] {standard_task_runner.py:105} INFO - Job 28: Subtask scrape_twitter_task
[2024-11-20T10:41:09.003+0700] {task_command.py:467} INFO - Running <TaskInstance: scrape_twitter.scrape_twitter_task manual__2024-11-20T03:40:58.859380+00:00 [running]> on host fabian4819-VirtualBox
[2024-11-20T10:41:09.326+0700] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='scrape_twitter' AIRFLOW_CTX_TASK_ID='scrape_twitter_task' AIRFLOW_CTX_EXECUTION_DATE='2024-11-20T03:40:58.859380+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-20T03:40:58.859380+00:00'
[2024-11-20T10:41:09.329+0700] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-11-20T10:41:09.330+0700] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-11-20T10:41:09.330+0700] {logging_mixin.py:190} INFO - Current task name:scrape_twitter_task state:running start_date:2024-11-20 03:41:08.696724+00:00
[2024-11-20T10:41:09.331+0700] {logging_mixin.py:190} INFO - Dag name:scrape_twitter and current dag run status:running
[2024-11-20T10:41:09.331+0700] {taskinstance.py:731} INFO - ::endgroup::
[2024-11-20T10:41:29.217+0700] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/fabian4819/REKAYASA DATA/final-exam-etl-pipeline-project/airflow-env/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/fabian4819/REKAYASA DATA/final-exam-etl-pipeline-project/airflow-env/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/fabian4819/REKAYASA DATA/final-exam-etl-pipeline-project/airflow-env/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/fabian4819/REKAYASA DATA/final-exam-etl-pipeline-project/airflow-env/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/fabian4819/REKAYASA DATA/final-exam-etl-pipeline-project/airflow-env/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/fabian4819/REKAYASA DATA/final-exam-etl-pipeline-project/airflow-env/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/fabian4819/REKAYASA DATA/final-exam-etl-pipeline-project/airflow-env/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/fabian4819/REKAYASA DATA/final-exam-etl-pipeline-project/airflow/dags/scrape_twitter_dag.py", line 40, in run_scrape_twitter
    scrape_twitter(search_term)  # Panggil fungsi dari scrapping-twitter.py
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/fabian4819/REKAYASA DATA/final-exam-etl-pipeline-project/notebooks/scrapping-twitter.py", line 27, in scrape_twitter
    raise ValueError("TWITTER_AUTH_TOKEN environment variable is not set. Please set it before running the script.")
ValueError: TWITTER_AUTH_TOKEN environment variable is not set. Please set it before running the script.
[2024-11-20T10:41:29.311+0700] {logging_mixin.py:190} INFO - Task instance in failure state
[2024-11-20T10:41:29.312+0700] {logging_mixin.py:190} INFO - Task start:2024-11-20 03:41:08.696724+00:00 end:2024-11-20 03:41:29.310296+00:00 duration:20.613572
[2024-11-20T10:41:29.312+0700] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): scrape_twitter_task> dag:<DAG: scrape_twitter> dagrun:<DagRun scrape_twitter @ 2024-11-20 03:40:58.859380+00:00: manual__2024-11-20T03:40:58.859380+00:00, state:running, queued_at: 2024-11-20 03:40:58.937483+00:00. externally triggered: True>
[2024-11-20T10:41:29.313+0700] {logging_mixin.py:190} INFO - Failure caused by TWITTER_AUTH_TOKEN environment variable is not set. Please set it before running the script.
[2024-11-20T10:41:29.313+0700] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=scrape_twitter, task_id=scrape_twitter_task, run_id=manual__2024-11-20T03:40:58.859380+00:00, execution_date=20241120T034058, start_date=20241120T034108, end_date=20241120T034129
[2024-11-20T10:41:29.384+0700] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-11-20T10:41:29.387+0700] {standard_task_runner.py:124} ERROR - Failed to execute job 28 for task scrape_twitter_task (TWITTER_AUTH_TOKEN environment variable is not set. Please set it before running the script.; 126999)
Traceback (most recent call last):
  File "/home/fabian4819/REKAYASA DATA/final-exam-etl-pipeline-project/airflow-env/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/fabian4819/REKAYASA DATA/final-exam-etl-pipeline-project/airflow-env/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/fabian4819/REKAYASA DATA/final-exam-etl-pipeline-project/airflow-env/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/fabian4819/REKAYASA DATA/final-exam-etl-pipeline-project/airflow-env/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/fabian4819/REKAYASA DATA/final-exam-etl-pipeline-project/airflow-env/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/fabian4819/REKAYASA DATA/final-exam-etl-pipeline-project/airflow-env/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/fabian4819/REKAYASA DATA/final-exam-etl-pipeline-project/airflow-env/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/fabian4819/REKAYASA DATA/final-exam-etl-pipeline-project/airflow-env/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/fabian4819/REKAYASA DATA/final-exam-etl-pipeline-project/airflow-env/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/fabian4819/REKAYASA DATA/final-exam-etl-pipeline-project/airflow-env/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/fabian4819/REKAYASA DATA/final-exam-etl-pipeline-project/airflow-env/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/fabian4819/REKAYASA DATA/final-exam-etl-pipeline-project/airflow-env/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/fabian4819/REKAYASA DATA/final-exam-etl-pipeline-project/airflow-env/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/fabian4819/REKAYASA DATA/final-exam-etl-pipeline-project/airflow-env/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/fabian4819/REKAYASA DATA/final-exam-etl-pipeline-project/airflow-env/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/fabian4819/REKAYASA DATA/final-exam-etl-pipeline-project/airflow-env/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/fabian4819/REKAYASA DATA/final-exam-etl-pipeline-project/airflow-env/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/fabian4819/REKAYASA DATA/final-exam-etl-pipeline-project/airflow-env/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/fabian4819/REKAYASA DATA/final-exam-etl-pipeline-project/airflow/dags/scrape_twitter_dag.py", line 40, in run_scrape_twitter
    scrape_twitter(search_term)  # Panggil fungsi dari scrapping-twitter.py
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/fabian4819/REKAYASA DATA/final-exam-etl-pipeline-project/notebooks/scrapping-twitter.py", line 27, in scrape_twitter
    raise ValueError("TWITTER_AUTH_TOKEN environment variable is not set. Please set it before running the script.")
ValueError: TWITTER_AUTH_TOKEN environment variable is not set. Please set it before running the script.
[2024-11-20T10:41:29.518+0700] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-11-20T10:41:29.608+0700] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-11-20T10:41:29.611+0700] {local_task_job_runner.py:245} INFO - ::endgroup::
