[2024-11-20T10:25:36.197+0700] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-11-20T10:25:36.372+0700] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: scrape_twitter.scrape_twitter_task manual__2024-11-20T03:25:23.639414+00:00 [queued]>
[2024-11-20T10:25:36.452+0700] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: scrape_twitter.scrape_twitter_task manual__2024-11-20T03:25:23.639414+00:00 [queued]>
[2024-11-20T10:25:36.452+0700] {taskinstance.py:2866} INFO - Starting attempt 1 of 2
[2024-11-20T10:25:36.558+0700] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): scrape_twitter_task> on 2024-11-20 03:25:23.639414+00:00
[2024-11-20T10:25:36.638+0700] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'scrape_twitter', 'scrape_twitter_task', 'manual__2024-11-20T03:25:23.639414+00:00', '--job-id', '21', '--raw', '--subdir', 'DAGS_FOLDER/scrape_twitter_dag.py', '--cfg-path', '/tmp/tmp8a64vj1m']
[2024-11-20T10:25:36.648+0700] {standard_task_runner.py:105} INFO - Job 21: Subtask scrape_twitter_task
[2024-11-20T10:25:36.654+0700] {logging_mixin.py:190} WARNING - /home/fabian4819/REKAYASA DATA/final-exam-etl-pipeline-project/airflow-env/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=110468) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-11-20T10:25:36.664+0700] {standard_task_runner.py:72} INFO - Started process 110808 to run task
[2024-11-20T10:25:37.039+0700] {task_command.py:467} INFO - Running <TaskInstance: scrape_twitter.scrape_twitter_task manual__2024-11-20T03:25:23.639414+00:00 [running]> on host fabian4819-VirtualBox
[2024-11-20T10:25:37.407+0700] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='scrape_twitter' AIRFLOW_CTX_TASK_ID='scrape_twitter_task' AIRFLOW_CTX_EXECUTION_DATE='2024-11-20T03:25:23.639414+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-20T03:25:23.639414+00:00'
[2024-11-20T10:25:37.412+0700] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-11-20T10:25:37.413+0700] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-11-20T10:25:37.413+0700] {logging_mixin.py:190} INFO - Current task name:scrape_twitter_task state:running start_date:2024-11-20 03:25:36.372999+00:00
[2024-11-20T10:25:37.419+0700] {logging_mixin.py:190} INFO - Dag name:scrape_twitter and current dag run status:running
[2024-11-20T10:25:37.420+0700] {taskinstance.py:731} INFO - ::endgroup::
[2024-11-20T10:25:38.941+0700] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/fabian4819/REKAYASA DATA/final-exam-etl-pipeline-project/airflow-env/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/fabian4819/REKAYASA DATA/final-exam-etl-pipeline-project/airflow-env/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/fabian4819/REKAYASA DATA/final-exam-etl-pipeline-project/airflow-env/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/fabian4819/REKAYASA DATA/final-exam-etl-pipeline-project/airflow-env/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/fabian4819/REKAYASA DATA/final-exam-etl-pipeline-project/airflow-env/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/fabian4819/REKAYASA DATA/final-exam-etl-pipeline-project/airflow-env/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/fabian4819/REKAYASA DATA/final-exam-etl-pipeline-project/airflow-env/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/fabian4819/REKAYASA DATA/final-exam-etl-pipeline-project/airflow/dags/scrape_twitter_dag.py", line 40, in run_scrape_twitter
    scrape_twitter(search_term)  # Panggil fungsi dari scrapping-twitter.py
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/fabian4819/REKAYASA DATA/final-exam-etl-pipeline-project/notebooks/scrapping-twitter.py", line 20, in scrape_twitter
    driver = webdriver.Chrome()
             ^^^^^^^^^^^^^^^^^^
  File "/home/fabian4819/REKAYASA DATA/final-exam-etl-pipeline-project/airflow-env/lib/python3.12/site-packages/selenium/webdriver/chrome/webdriver.py", line 45, in __init__
    super().__init__(
  File "/home/fabian4819/REKAYASA DATA/final-exam-etl-pipeline-project/airflow-env/lib/python3.12/site-packages/selenium/webdriver/chromium/webdriver.py", line 66, in __init__
    super().__init__(command_executor=executor, options=options)
  File "/home/fabian4819/REKAYASA DATA/final-exam-etl-pipeline-project/airflow-env/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py", line 238, in __init__
    self.start_session(capabilities)
  File "/home/fabian4819/REKAYASA DATA/final-exam-etl-pipeline-project/airflow-env/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py", line 325, in start_session
    response = self.execute(Command.NEW_SESSION, caps)["value"]
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/fabian4819/REKAYASA DATA/final-exam-etl-pipeline-project/airflow-env/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py", line 380, in execute
    self.error_handler.check_response(response)
  File "/home/fabian4819/REKAYASA DATA/final-exam-etl-pipeline-project/airflow-env/lib/python3.12/site-packages/selenium/webdriver/remote/errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: session not created: Chrome failed to start: exited normally.
  (session not created: DevToolsActivePort file doesn't exist)
  (The process started from chrome location /home/fabian4819/.cache/selenium/chrome/linux64/131.0.6778.85/chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
Stacktrace:
#0 0x5a7c441fc31a <unknown>
#1 0x5a7c43d126e0 <unknown>
#2 0x5a7c43d49dc8 <unknown>
#3 0x5a7c43d45926 <unknown>
#4 0x5a7c43d916f6 <unknown>
#5 0x5a7c43d90d46 <unknown>
#6 0x5a7c43d85203 <unknown>
#7 0x5a7c43d53cc0 <unknown>
#8 0x5a7c43d54c9e <unknown>
#9 0x5a7c441c9d0b <unknown>
#10 0x5a7c441cdc92 <unknown>
#11 0x5a7c441b6b3c <unknown>
#12 0x5a7c441ce807 <unknown>
#13 0x5a7c4419c0df <unknown>
#14 0x5a7c441eb578 <unknown>
#15 0x5a7c441eb740 <unknown>
#16 0x5a7c441fb196 <unknown>
#17 0x7ee8a6c9ca94 <unknown>
#18 0x7ee8a6d29c3c <unknown>

[2024-11-20T10:25:39.002+0700] {logging_mixin.py:190} INFO - Task instance in failure state
[2024-11-20T10:25:39.003+0700] {logging_mixin.py:190} INFO - Task start:2024-11-20 03:25:36.372999+00:00 end:2024-11-20 03:25:39.001424+00:00 duration:2.628425
[2024-11-20T10:25:39.003+0700] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): scrape_twitter_task> dag:<DAG: scrape_twitter> dagrun:<DagRun scrape_twitter @ 2024-11-20 03:25:23.639414+00:00: manual__2024-11-20T03:25:23.639414+00:00, state:running, queued_at: 2024-11-20 03:25:23.690875+00:00. externally triggered: True>
[2024-11-20T10:25:39.004+0700] {logging_mixin.py:190} INFO - Failure caused by Message: session not created: Chrome failed to start: exited normally.
  (session not created: DevToolsActivePort file doesn't exist)
  (The process started from chrome location /home/fabian4819/.cache/selenium/chrome/linux64/131.0.6778.85/chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
Stacktrace:
#0 0x5a7c441fc31a <unknown>
#1 0x5a7c43d126e0 <unknown>
#2 0x5a7c43d49dc8 <unknown>
#3 0x5a7c43d45926 <unknown>
#4 0x5a7c43d916f6 <unknown>
#5 0x5a7c43d90d46 <unknown>
#6 0x5a7c43d85203 <unknown>
#7 0x5a7c43d53cc0 <unknown>
#8 0x5a7c43d54c9e <unknown>
#9 0x5a7c441c9d0b <unknown>
#10 0x5a7c441cdc92 <unknown>
#11 0x5a7c441b6b3c <unknown>
#12 0x5a7c441ce807 <unknown>
#13 0x5a7c4419c0df <unknown>
#14 0x5a7c441eb578 <unknown>
#15 0x5a7c441eb740 <unknown>
#16 0x5a7c441fb196 <unknown>
#17 0x7ee8a6c9ca94 <unknown>
#18 0x7ee8a6d29c3c <unknown>
[2024-11-20T10:25:39.004+0700] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=scrape_twitter, task_id=scrape_twitter_task, run_id=manual__2024-11-20T03:25:23.639414+00:00, execution_date=20241120T032523, start_date=20241120T032536, end_date=20241120T032539
[2024-11-20T10:25:39.048+0700] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-11-20T10:25:39.049+0700] {standard_task_runner.py:124} ERROR - Failed to execute job 21 for task scrape_twitter_task (Message: session not created: Chrome failed to start: exited normally.
  (session not created: DevToolsActivePort file doesn't exist)
  (The process started from chrome location /home/fabian4819/.cache/selenium/chrome/linux64/131.0.6778.85/chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
Stacktrace:
#0 0x5a7c441fc31a <unknown>
#1 0x5a7c43d126e0 <unknown>
#2 0x5a7c43d49dc8 <unknown>
#3 0x5a7c43d45926 <unknown>
#4 0x5a7c43d916f6 <unknown>
#5 0x5a7c43d90d46 <unknown>
#6 0x5a7c43d85203 <unknown>
#7 0x5a7c43d53cc0 <unknown>
#8 0x5a7c43d54c9e <unknown>
#9 0x5a7c441c9d0b <unknown>
#10 0x5a7c441cdc92 <unknown>
#11 0x5a7c441b6b3c <unknown>
#12 0x5a7c441ce807 <unknown>
#13 0x5a7c4419c0df <unknown>
#14 0x5a7c441eb578 <unknown>
#15 0x5a7c441eb740 <unknown>
#16 0x5a7c441fb196 <unknown>
#17 0x7ee8a6c9ca94 <unknown>
#18 0x7ee8a6d29c3c <unknown>
; 110808)
Traceback (most recent call last):
  File "/home/fabian4819/REKAYASA DATA/final-exam-etl-pipeline-project/airflow-env/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/fabian4819/REKAYASA DATA/final-exam-etl-pipeline-project/airflow-env/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/fabian4819/REKAYASA DATA/final-exam-etl-pipeline-project/airflow-env/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/fabian4819/REKAYASA DATA/final-exam-etl-pipeline-project/airflow-env/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/fabian4819/REKAYASA DATA/final-exam-etl-pipeline-project/airflow-env/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/fabian4819/REKAYASA DATA/final-exam-etl-pipeline-project/airflow-env/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/fabian4819/REKAYASA DATA/final-exam-etl-pipeline-project/airflow-env/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/fabian4819/REKAYASA DATA/final-exam-etl-pipeline-project/airflow-env/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/fabian4819/REKAYASA DATA/final-exam-etl-pipeline-project/airflow-env/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/fabian4819/REKAYASA DATA/final-exam-etl-pipeline-project/airflow-env/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/fabian4819/REKAYASA DATA/final-exam-etl-pipeline-project/airflow-env/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/fabian4819/REKAYASA DATA/final-exam-etl-pipeline-project/airflow-env/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/fabian4819/REKAYASA DATA/final-exam-etl-pipeline-project/airflow-env/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/fabian4819/REKAYASA DATA/final-exam-etl-pipeline-project/airflow-env/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/fabian4819/REKAYASA DATA/final-exam-etl-pipeline-project/airflow-env/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/fabian4819/REKAYASA DATA/final-exam-etl-pipeline-project/airflow-env/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/fabian4819/REKAYASA DATA/final-exam-etl-pipeline-project/airflow-env/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/fabian4819/REKAYASA DATA/final-exam-etl-pipeline-project/airflow-env/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/fabian4819/REKAYASA DATA/final-exam-etl-pipeline-project/airflow/dags/scrape_twitter_dag.py", line 40, in run_scrape_twitter
    scrape_twitter(search_term)  # Panggil fungsi dari scrapping-twitter.py
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/fabian4819/REKAYASA DATA/final-exam-etl-pipeline-project/notebooks/scrapping-twitter.py", line 20, in scrape_twitter
    driver = webdriver.Chrome()
             ^^^^^^^^^^^^^^^^^^
  File "/home/fabian4819/REKAYASA DATA/final-exam-etl-pipeline-project/airflow-env/lib/python3.12/site-packages/selenium/webdriver/chrome/webdriver.py", line 45, in __init__
    super().__init__(
  File "/home/fabian4819/REKAYASA DATA/final-exam-etl-pipeline-project/airflow-env/lib/python3.12/site-packages/selenium/webdriver/chromium/webdriver.py", line 66, in __init__
    super().__init__(command_executor=executor, options=options)
  File "/home/fabian4819/REKAYASA DATA/final-exam-etl-pipeline-project/airflow-env/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py", line 238, in __init__
    self.start_session(capabilities)
  File "/home/fabian4819/REKAYASA DATA/final-exam-etl-pipeline-project/airflow-env/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py", line 325, in start_session
    response = self.execute(Command.NEW_SESSION, caps)["value"]
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/fabian4819/REKAYASA DATA/final-exam-etl-pipeline-project/airflow-env/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py", line 380, in execute
    self.error_handler.check_response(response)
  File "/home/fabian4819/REKAYASA DATA/final-exam-etl-pipeline-project/airflow-env/lib/python3.12/site-packages/selenium/webdriver/remote/errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: session not created: Chrome failed to start: exited normally.
  (session not created: DevToolsActivePort file doesn't exist)
  (The process started from chrome location /home/fabian4819/.cache/selenium/chrome/linux64/131.0.6778.85/chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
Stacktrace:
#0 0x5a7c441fc31a <unknown>
#1 0x5a7c43d126e0 <unknown>
#2 0x5a7c43d49dc8 <unknown>
#3 0x5a7c43d45926 <unknown>
#4 0x5a7c43d916f6 <unknown>
#5 0x5a7c43d90d46 <unknown>
#6 0x5a7c43d85203 <unknown>
#7 0x5a7c43d53cc0 <unknown>
#8 0x5a7c43d54c9e <unknown>
#9 0x5a7c441c9d0b <unknown>
#10 0x5a7c441cdc92 <unknown>
#11 0x5a7c441b6b3c <unknown>
#12 0x5a7c441ce807 <unknown>
#13 0x5a7c4419c0df <unknown>
#14 0x5a7c441eb578 <unknown>
#15 0x5a7c441eb740 <unknown>
#16 0x5a7c441fb196 <unknown>
#17 0x7ee8a6c9ca94 <unknown>
#18 0x7ee8a6d29c3c <unknown>

[2024-11-20T10:25:39.107+0700] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-11-20T10:25:39.226+0700] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-11-20T10:25:39.231+0700] {local_task_job_runner.py:245} INFO - ::endgroup::
